<a href="https://colab.research.google.com/github/mahirshadid2point0/machine-learning-cse-4877-4878/blob/main/week3_c1_c2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# CSE-4878: Machine Learning and Data Mining Lab
# Week 3: Data Preprocessing
#
# Class 1: Data Quality and Cleaning
# Class 2: Transformation, Normalization and Encoding

In [2]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!


In [19]:
# Class 1

df = pd.DataFrame({
    "Name": ["Rahim", "Karim", "Sakib", "Nusrat", "Sakib", "Tanvir", "Mim", "Rafi"],
    "Age": [21, 22, np.nan, 24, 24, 25, 120, 23],
    "City": ["Dhaka", "dhaka", "Dhaka", "Chattogram",
             "Chattogram", "Dhaka", "Dhaka", "Dhaka"],
    "Score": [75, 81, 79, np.nan, 85, 90, 88, 90]
})

df

,Name,Age,City,Score
0,Rahim,21.0,Dhaka,75.0
1,Karim,22.0,dhaka,81.0
2,Sakib,NaN,Dhaka,79.0
3,Nusrat,24.0,Chattogram,NaN
4,Sakib,24.0,Chattogram,85.0
5,Tanvir,25.0,Dhaka,90.0
6,Mim,120.0,Dhaka,88.0
7,Rafi,23.0,Dhaka,90.0


In [4]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nData types:")
print(df.dtypes)

Number of rows: 8
Number of columns: 4

Data types:
Name      object
Age      float64
City      object
Score    float64
dtype: object


In [5]:
print("Missing values in each column:")
print(df.isna().sum())

Missing values in each column:
Name     0
Age      1
City     0
Score    1
dtype: int64


In [6]:
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0


In [7]:
print("Duplicate records:")
print(df[df.duplicated()])

Duplicate records:
Empty DataFrame
Columns: [Name, Age, City, Score]
Index: []


In [8]:
print("Unique city values:")
print(df["City"].unique())

Unique city values:
['Dhaka' 'dhaka' 'Chattogram']


In [9]:
df["City"] = (
    df["City"]
    .str.strip()
    .str.lower()
    .str.title()
)

print(df["City"].unique())

['Dhaka' 'Chattogram']


In [10]:
print(df["Age"].describe())

count      7.000000
mean      37.000000
std       36.624218
min       21.000000
25%       22.500000
50%       24.000000
75%       24.500000
max      120.000000
Name: Age, dtype: float64


In [11]:
Q1 = df["Age"].quantile(0.25)
Q3 = df["Age"].quantile(0.75)

IQR = Q3 - Q1

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)

Q1 = 22.5
Q3 = 24.5
IQR = 2.0


In [12]:
lower_fence = Q1 - 1.5 * IQR
upper_fence = Q3 + 1.5 * IQR

print("Lower fence =", lower_fence)
print("Upper fence =", upper_fence)

Lower fence = 19.5
Upper fence = 27.5


In [13]:
outlier_mask = (
    (df["Age"] < lower_fence) |
    (df["Age"] > upper_fence)
)

print("Possible outliers:")
print(df[outlier_mask])

Possible outliers:
  Name    Age   City  Score
6  Mim  120.0  Dhaka   88.0


In [14]:
print(df[["Name", "Age"]][outlier_mask])

  Name    Age
6  Mim  120.0


In [15]:
df_clean = df.copy()

df_clean["Age"] = df_clean["Age"].fillna(
    df_clean["Age"].median()
)

df_clean["Score"] = df_clean["Score"].fillna(
    df_clean["Score"].median()
)

df_clean

,Name,Age,City,Score
0,Rahim,21.0,Dhaka,75.0
1,Karim,22.0,Dhaka,81.0
2,Sakib,24.0,Dhaka,79.0
3,Nusrat,24.0,Chattogram,85.0
4,Sakib,24.0,Chattogram,85.0
5,Tanvir,25.0,Dhaka,90.0
6,Mim,120.0,Dhaka,88.0
7,Rafi,23.0,Dhaka,90.0


In [16]:
print("Rows before removing duplicates:", len(df_clean))

df_clean = df_clean.drop_duplicates()

print("Rows after removing duplicates:", len(df_clean))

Rows before removing duplicates: 8
Rows after removing duplicates: 8


In [18]:
print("Original dataset:")
print(df)

print("\nCleaned dataset:")
print(df_clean)

Original dataset:
     Name    Age        City  Score
0   Rahim   21.0       Dhaka   75.0
1   Karim   22.0       Dhaka   81.0
2   Sakib    NaN       Dhaka   79.0
3  Nusrat   24.0  Chattogram    NaN
4   Sakib   24.0  Chattogram   85.0
5  Tanvir   25.0       Dhaka   90.0
6     Mim  120.0       Dhaka   88.0
7    Rafi   23.0       Dhaka   90.0

Cleaned dataset:
     Name    Age        City  Score
0   Rahim   21.0       Dhaka   75.0
1   Karim   22.0       Dhaka   81.0
2   Sakib   24.0       Dhaka   79.0
3  Nusrat   24.0  Chattogram   85.0
4   Sakib   24.0  Chattogram   85.0
5  Tanvir   25.0       Dhaka   90.0
6     Mim  120.0       Dhaka   88.0
7    Rafi   23.0       Dhaka   90.0


In [28]:
# Class 2

data = pd.DataFrame({
    "Age": [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
    "Income": [20, 22, 25, 27, 30, 34, 38, 42, 50, 60],
    "City": ["A", "A", "B", "B", "C", "C", "A", "B", "C", "A"],
    "Target": [0, 0, 0, 1, 1, 1, 1, 1, 1, 1]
})

data

,Age,Income,City,Target
0,20,20,A,0
1,21,22,A,0
2,22,25,B,0
3,23,27,B,1
4,24,30,C,1
5,25,34,C,1
6,26,38,A,1
7,27,42,B,1
8,28,50,C,1
9,29,60,A,1


In [21]:
X = data.drop(columns="Target")
y = data["Target"]

print("Features:")
print(X)

print("\nTarget:")
print(y)

Features:
   Age  Income City
0   20      20    A
1   21      22    A
2   22      25    B
3   23      27    B
4   24      30    C
5   25      34    C
6   26      38    A
7   27      42    B
8   28      50    C
9   29      60    A

Target:
0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
Name: Target, dtype: int64


In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("Training data:")
print(X_train)

print("\nTesting data:")
print(X_test)

Training data:
   Age  Income City
8   28      50    C
1   21      22    A
0   20      20    A
4   24      30    C
3   23      27    B
9   29      60    A
6   26      38    A

Testing data:
   Age  Income City
2   22      25    B
5   25      34    C
7   27      42    B


In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(
    X_train[["Age", "Income"]]
)

X_test_scaled = scaler.transform(
    X_test[["Age", "Income"]]
)

print("Scaled training data:")
print(X_train_scaled)

Scaled training data:
[[ 1.13169683  1.06292942]
 [-1.08642895 -0.95973239]
 [-1.40330406 -1.10420823]
 [-0.13580362 -0.38182902]
 [-0.45267873 -0.59854278]
 [ 1.44857194  1.78530864]
 [ 0.4979466   0.19607436]]


In [24]:
print("Before scaling:")
print(X_train[["Age", "Income"]].head())

print("\nAfter scaling:")
print(X_train_scaled[:5])

Before scaling:
   Age  Income
8   28      50
1   21      22
0   20      20
4   24      30
3   23      27

After scaling:
[[ 1.13169683  1.06292942]
 [-1.08642895 -0.95973239]
 [-1.40330406 -1.10420823]
 [-0.13580362 -0.38182902]
 [-0.45267873 -0.59854278]]


In [25]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()

X_train_minmax = minmax.fit_transform(
    X_train[["Age", "Income"]]
)

X_test_minmax = minmax.transform(
    X_test[["Age", "Income"]]
)

print(X_train_minmax)

[[0.88888889 0.75      ]
 [0.11111111 0.05      ]
 [0.         0.        ]
 [0.44444444 0.25      ]
 [0.33333333 0.175     ]
 [1.         1.        ]
 [0.66666667 0.45      ]]


In [26]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

city_encoded = encoder.fit_transform(
    X_train[["City"]]
)

print(city_encoded)

[[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [27]:
print("Categories:")
print(encoder.categories_)

Categories:
[array(['A', 'B', 'C'], dtype=object)]


In [29]:
from sklearn.compose import ColumnTransformer

numeric_features = ["Age", "Income"]
categorical_features = ["City"]

preprocessor = ColumnTransformer(
    transformers=[
        ("numeric", StandardScaler(), numeric_features),
        ("categorical", OneHotEncoder(
            handle_unknown="ignore"
        ), categorical_features)
    ]
)

In [31]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

print("Training shape:", X_train_processed.shape)
print("Testing shape:", X_test_processed.shape)

Training shape: (7, 5)
Testing shape: (3, 5)


In [32]:
wrong_scaler = StandardScaler()

# WRONG!
X_wrong = wrong_scaler.fit_transform(
    X[["Age", "Income"]]
)

print(X_wrong[:5])

[[-1.5666989  -1.21181278]
 [-1.21854359 -1.0480543 ]
 [-0.87038828 -0.80241657]
 [-0.52223297 -0.63865809]
 [-0.17407766 -0.39302036]]


In [33]:
right_scaler = StandardScaler()

# Learn parameters ONLY from training data
right_scaler.fit(X_train[["Age", "Income"]])

# Transform training data
X_train_right = right_scaler.transform(
    X_train[["Age", "Income"]]
)

# Transform test data
X_test_right = right_scaler.transform(
    X_test[["Age", "Income"]]
)

print("Correct preprocessing completed!")

Correct preprocessing completed!


In [34]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LogisticRegression())
])

pipeline.fit(X_train, y_train)

accuracy = pipeline.score(X_test, y_test)

print("Test Accuracy:", accuracy)

Test Accuracy: 0.6666666666666666


In [35]:
comparison = pd.DataFrame({
    "Original Age": X_train["Age"].values,
    "Standardized Age": X_train_scaled[:, 0],
    "MinMax Age": X_train_minmax[:, 0]
})

comparison

,Original Age,Standardized Age,MinMax Age
0,28,1.131697,0.888889
1,21,-1.086429,0.111111
2,20,-1.403304,0.000000
3,24,-0.135804,0.444444
4,23,-0.452679,0.333333
5,29,1.448572,1.000000
6,26,0.497947,0.666667
